<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Lenovo-PC" name="com.cts.exception.CustomExceptionHandlerTest" tests="4" failures="0" timestamp="2020-04-23T14:06:59 IST" time="3.057" errors="0">
  <testcase name="methodArgumentNotValidTest" time="0.783" classname="com.cts.exception.CustomExceptionHandlerTest"/>
  <system-out/>
  <testcase name="handleAllExceptionTest" time="0.755" classname="com.cts.exception.CustomExceptionHandlerTest"/>
  <system-out/>
  <testcase name="handleInternalServerExceptionTest" time="0.750" classname="com.cts.exception.CustomExceptionHandlerTest"/>
  <system-out/>
  <testcase name="handleRecordNotFoundExceptionTest" time="0.769" classname="com.cts.exception.CustomExceptionHandlerTest"/>
  <system-out/>
</testsuite> <!-- com.cts.exception.CustomExceptionHandlerTest -->
